server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wzycgyz/aispringcloud2.git
          searchPaths: config
          username: wzycgyz
          password: zhx8502668
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/